spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.hostinger.com
    port: 587
    username: no-reply@chateaudecibioux.fr
    password: NoReply@Cib2024
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        
app:
  security:
    jwt:
      JWT_SECRET: "Z@5BbDw8Jr2{&XC<k[+K6)Mq73j4E]uV_yaRFg^eU-GP}d9N%f"
      EXPIRES_AT: 1_800_000
    cors:
      serverName: "http://localhost:4200"
  datainit:
    enabled: true